import MainNavbar from "@layout/main-navbar/MainNavbar";
import "../styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MainFooter from "@layout/MainFooter";
import { cn } from "@utils";
import { ThemeProvider } from "@context/ThemeProvider";
import ReduxProvider from "@lib/redux/provider";
import PersistLogin from "@components/PersistLogin";
import VerifyEmailMsg from "@components/VerifyEmailMsg";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Authentication App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(inter.className, "flex flex-col min-h-screen")}>
        <ReduxProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <PersistLogin>
              <MainNavbar />
              <VerifyEmailMsg className="mb-8" />
              <main className="flex-1">{children}</main>
              <MainFooter />
            </PersistLogin>
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
};

export default RootLayout;
